version: "3.10"

services:
  db:
    container_name: db
    image: postgres:15
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    container_name: admin_panel
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
    entrypoint: /entrypoint.sh